
variable "subnet_name" {}
variable "key_pair" {}
variable "ec2_ami_id" {}
variable "instance_type" {}
variable "ec2-server-name" {}
variable "ec2-server-environment" {}
variable "ec2-service-owner" {}
variable "key_pair_name" {}
variable "key_pair_filename" {}
variable "vpc_name" {}
variable "aws_access_key_id" {}
variable "aws_secret_key_id" {}
variable "aws_region" {}
variable "ec2_security_group_name" {}
variable "ec2_security_group_description" {}
variable "ingress_tls_from_vpc_description" {}
variable "s3_bucket_name" {}
variable "creator_name" {}
variable "environment_name" {}
variable "managedby" {}
variable "s3_bucket_name" {}